config/routes.rb
Rails.application.routes.draw do

	resources :projects, only: [:index, :show]
	namespace :casein do
		resources :projects
	end

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casein/projects_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class ProjectsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Projects'
  		@projects = Project.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View project'
      @project = Project.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new project'
    	@project = Project.new
    end

    def create
      @project = Project.new project_params
    
      if @project.save
        flash[:notice] = 'Project created'
        redirect_to casein_projects_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new project'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update project'
      
      @project = Project.find params[:id]
    
      if @project.update_attributes project_params
        flash[:notice] = 'Project has been updated'
        redirect_to casein_projects_path
      else
        flash.now[:warning] = 'There were problems when trying to update this project'
        render :action => :show
      end
    end
 
    def destroy
      @project = Project.find params[:id]

      @project.destroy
      flash[:notice] = 'Project has been deleted'
      redirect_to casein_projects_path
    end
  
    private
      
      def project_params
        params.require(:project).permit(:name, :body, :order)
      end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @kitties = "Loki is cute"
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper

    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end

    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :projects, :action => :index
    end

    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end

    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

  end
end

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-projects"><%= link_to "Projects", casein_projects_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/casein/projects/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-sm-10">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-sm-2">
		<%= casein_text_field f, f.object, :order %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_area_big f, f.object, :body, options = { class: "wysihtml5" } %>
	</div>

</div>

app/views/casein/projects/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Body", :body %></th>
			<th><%= casein_sort_link "Order", :order %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% projects.each do |project| %>
		<tr>
			<td><%= casein_table_cell_link project.name, casein_project_path(project) %></td>
			<td><%= casein_table_cell_link project.body, casein_project_path(project) %></td>
			<td><%= casein_table_cell_link project.order, casein_project_path(project) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_project_path(project), :method => :delete, :data => { :confirm => "Are you sure you want to delete this project?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/projects/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Projects<%= casein_pagination_details @projects %></h2>

<%= render :partial => 'casein/projects/table', :locals => { :projects => @projects } %>

<div class="text-center">
	<%= will_paginate @projects %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new project".html_safe, new_casein_project_path %></li>

<% end %>

app/views/casein/projects/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new project</h2>

<%= form_for @project, :url => casein_projects_path do |f| %>
	
	<%= render :partial => 'casein/projects/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_projects_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new project", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_projects_path %></li>
<% end %>

app/views/casein/projects/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View project</h2>

<%= form_for @project, :url => casein_project_path(@project) do |f| %>

	<%= render :partial => 'casein/projects/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_projects_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_projects_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>